//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Settings/Input/StandardInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Settings/Input/StandardInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @StandardInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @StandardInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""StandardInput"",
    ""maps"": [
        {
            ""name"": ""GameplayMap"",
            ""id"": ""e02f8973-846d-409a-99ec-180914ef7e94"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""cbe06dbc-653f-4912-9817-8c2ab3d1abac"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell1"",
                    ""type"": ""Button"",
                    ""id"": ""5829ae3a-0eec-44bc-84e4-68e736b86d0d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell2"",
                    ""type"": ""Button"",
                    ""id"": ""8ff526d7-9c9b-4ce8-a46e-e372309f5af5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell3"",
                    ""type"": ""Button"",
                    ""id"": ""f5872b1a-35d7-42d8-88ea-92ef1ad8a4c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell4"",
                    ""type"": ""Button"",
                    ""id"": ""b4afbaec-2bf2-47dc-bea6-d6983bf8883c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell5"",
                    ""type"": ""Button"",
                    ""id"": ""33ea8082-53de-40a9-a3d3-14092ed3245a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell6"",
                    ""type"": ""Button"",
                    ""id"": ""58ed0b06-66b9-4011-8314-d6860802f4ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell7"",
                    ""type"": ""Button"",
                    ""id"": ""4ac86a5d-7bf7-4640-a2aa-f06e8a078384"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell8"",
                    ""type"": ""Button"",
                    ""id"": ""35cf17bf-c238-4001-a66f-06f2c7e2c93f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell9"",
                    ""type"": ""Button"",
                    ""id"": ""1212190a-a773-45c1-b3c9-e8c710d20451"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell10"",
                    ""type"": ""Button"",
                    ""id"": ""9b4849a6-c7a4-4f8f-b954-0bf5ba4976db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell11"",
                    ""type"": ""Button"",
                    ""id"": ""0854e6a2-413b-4c3a-aecc-cb0162c0788c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell12"",
                    ""type"": ""Button"",
                    ""id"": ""5b9e3f9d-6108-44de-a64f-1488c9701992"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell13"",
                    ""type"": ""Button"",
                    ""id"": ""20501e33-2d85-46db-8be6-14fc38dfa9ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell14"",
                    ""type"": ""Button"",
                    ""id"": ""6c2460c0-fa25-44f5-ae6d-05fe64ffd001"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell15"",
                    ""type"": ""Button"",
                    ""id"": ""1f982958-7c69-491b-b028-8c7f96a4a497"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spell16"",
                    ""type"": ""Button"",
                    ""id"": ""672d3e6b-8dcd-4c5c-a868-98a0551480ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""44516835-b257-46c8-abad-39ef22ace919"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AltClick"",
                    ""type"": ""Button"",
                    ""id"": ""bf412cd3-b50b-471d-b533-fea7edb37f24"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AltDoubleClick"",
                    ""type"": ""Button"",
                    ""id"": ""3f34b3c5-d9ec-4e7c-8fc8-3d66d3d00f20"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchAutoMode"",
                    ""type"": ""Button"",
                    ""id"": ""f54e5d04-26d1-4e01-896f-f076220314c1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShiftMouse"",
                    ""type"": ""Button"",
                    ""id"": ""44eeeadf-ff68-4132-9eb6-ad11777daf47"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollMouse"",
                    ""type"": ""Value"",
                    ""id"": ""56c07c89-6e78-47f8-b932-70b5db00d2fb"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ShowMenu"",
                    ""type"": ""Button"",
                    ""id"": ""112bcf04-8e2c-4c22-aefc-7382a08ded0c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShowSource"",
                    ""type"": ""Button"",
                    ""id"": ""ae4f2201-2591-45de-afdc-e1c7c5601321"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpaceMouse"",
                    ""type"": ""Button"",
                    ""id"": ""b70078f0-91e3-4ada-8895-f72efad55c5a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2d0c6642-bf07-4434-a7d6-bb22213037bc"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fa5d5556-e1e3-409d-96a2-8a7795801e7b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c81b48e7-d304-4369-99c5-26db511530ef"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8d868b83-7fbd-44ce-a281-8dead70048af"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c0debb60-51cd-4e66-86fa-417d78d6bdf6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""eda4cdab-6259-416c-91ff-dde9fd2b0cdb"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ce7edfa-1ea3-44b8-874d-84244bba45ae"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""518ff43c-f6e8-422a-a911-eeec2d0c3777"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5de434c9-0417-48c5-a0d3-5717c628ae97"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ced5113-28cb-4bdb-8c20-01686d1cb8ee"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""984c70d2-c9c4-413a-b26f-42a5d5de2e86"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""141e7693-f065-43c1-8a16-aa54d8c19def"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AltClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eac2a2b7-4104-4f0f-99ef-5bf36abdf2d0"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AltDoubleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c4f201f-0ec4-42b2-98ee-a58a8f3bcaae"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d35cb6df-5596-4f1b-a8c5-a4e8a556d07b"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64fa2808-d8d4-43d3-9816-8474de2d1239"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34f7e20e-e141-424a-a245-2f0151531024"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a41cbe4e-57f7-4f98-8f71-5e2bff61b6fe"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ff422cf-ae3e-4955-b4bb-2501b8977b4e"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell11"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9457032-943e-42a8-8565-fd4419d83569"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell12"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c411925-34ad-4835-ab89-e6f32fe667a8"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell13"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88a77d19-8d19-418c-80e6-b4c0237cd405"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell14"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4ba3cc3-18ee-476f-b768-925330c29dd6"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell15"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2cf1b2c-2382-421a-a59d-f9ce99e51c02"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spell16"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""d5e33051-6068-4ea6-85c8-54ce0a28b536"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchAutoMode"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""c172b242-1a92-487f-bc74-b3633c12faa4"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchAutoMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Binding"",
                    ""id"": ""9b0a6bad-5d24-466c-8339-532c7fe0a714"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchAutoMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""5beb35e5-391f-4ec7-8cb9-8a8a077b74ed"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollMouse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""cb192214-2d32-4867-9e53-e77c17ae05a4"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""705ed161-a4e2-4d36-91bd-16646c0a709c"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""9479e03f-3c70-4523-ab21-cb1060d3420a"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftMouse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""8c3d2e27-5ce9-4ba2-bb92-0267f969b6c2"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Binding"",
                    ""id"": ""a87490d1-8f08-49d5-9e9f-742014deb4f1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""adc473ee-2cf3-4d8c-ac0e-63c0e54c9528"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""f92e639c-e487-4c3e-87a1-3be633068231"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpaceMouse"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""46aa35e6-d059-4b96-afdb-ea738eb4377b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpaceMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Binding"",
                    ""id"": ""b731d84c-18e0-4525-bfb4-0b24e2420ce1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpaceMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f76ddb06-977e-4a58-aab6-f69283bda8c6"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowSource"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameplayMap
        m_GameplayMap = asset.FindActionMap("GameplayMap", throwIfNotFound: true);
        m_GameplayMap_Move = m_GameplayMap.FindAction("Move", throwIfNotFound: true);
        m_GameplayMap_Spell1 = m_GameplayMap.FindAction("Spell1", throwIfNotFound: true);
        m_GameplayMap_Spell2 = m_GameplayMap.FindAction("Spell2", throwIfNotFound: true);
        m_GameplayMap_Spell3 = m_GameplayMap.FindAction("Spell3", throwIfNotFound: true);
        m_GameplayMap_Spell4 = m_GameplayMap.FindAction("Spell4", throwIfNotFound: true);
        m_GameplayMap_Spell5 = m_GameplayMap.FindAction("Spell5", throwIfNotFound: true);
        m_GameplayMap_Spell6 = m_GameplayMap.FindAction("Spell6", throwIfNotFound: true);
        m_GameplayMap_Spell7 = m_GameplayMap.FindAction("Spell7", throwIfNotFound: true);
        m_GameplayMap_Spell8 = m_GameplayMap.FindAction("Spell8", throwIfNotFound: true);
        m_GameplayMap_Spell9 = m_GameplayMap.FindAction("Spell9", throwIfNotFound: true);
        m_GameplayMap_Spell10 = m_GameplayMap.FindAction("Spell10", throwIfNotFound: true);
        m_GameplayMap_Spell11 = m_GameplayMap.FindAction("Spell11", throwIfNotFound: true);
        m_GameplayMap_Spell12 = m_GameplayMap.FindAction("Spell12", throwIfNotFound: true);
        m_GameplayMap_Spell13 = m_GameplayMap.FindAction("Spell13", throwIfNotFound: true);
        m_GameplayMap_Spell14 = m_GameplayMap.FindAction("Spell14", throwIfNotFound: true);
        m_GameplayMap_Spell15 = m_GameplayMap.FindAction("Spell15", throwIfNotFound: true);
        m_GameplayMap_Spell16 = m_GameplayMap.FindAction("Spell16", throwIfNotFound: true);
        m_GameplayMap_Click = m_GameplayMap.FindAction("Click", throwIfNotFound: true);
        m_GameplayMap_AltClick = m_GameplayMap.FindAction("AltClick", throwIfNotFound: true);
        m_GameplayMap_AltDoubleClick = m_GameplayMap.FindAction("AltDoubleClick", throwIfNotFound: true);
        m_GameplayMap_SwitchAutoMode = m_GameplayMap.FindAction("SwitchAutoMode", throwIfNotFound: true);
        m_GameplayMap_ShiftMouse = m_GameplayMap.FindAction("ShiftMouse", throwIfNotFound: true);
        m_GameplayMap_ScrollMouse = m_GameplayMap.FindAction("ScrollMouse", throwIfNotFound: true);
        m_GameplayMap_ShowMenu = m_GameplayMap.FindAction("ShowMenu", throwIfNotFound: true);
        m_GameplayMap_ShowSource = m_GameplayMap.FindAction("ShowSource", throwIfNotFound: true);
        m_GameplayMap_SpaceMouse = m_GameplayMap.FindAction("SpaceMouse", throwIfNotFound: true);
    }

    ~@StandardInput()
    {
        UnityEngine.Debug.Assert(!m_GameplayMap.enabled, "This will cause a leak and performance issues, StandardInput.GameplayMap.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameplayMap
    private readonly InputActionMap m_GameplayMap;
    private List<IGameplayMapActions> m_GameplayMapActionsCallbackInterfaces = new List<IGameplayMapActions>();
    private readonly InputAction m_GameplayMap_Move;
    private readonly InputAction m_GameplayMap_Spell1;
    private readonly InputAction m_GameplayMap_Spell2;
    private readonly InputAction m_GameplayMap_Spell3;
    private readonly InputAction m_GameplayMap_Spell4;
    private readonly InputAction m_GameplayMap_Spell5;
    private readonly InputAction m_GameplayMap_Spell6;
    private readonly InputAction m_GameplayMap_Spell7;
    private readonly InputAction m_GameplayMap_Spell8;
    private readonly InputAction m_GameplayMap_Spell9;
    private readonly InputAction m_GameplayMap_Spell10;
    private readonly InputAction m_GameplayMap_Spell11;
    private readonly InputAction m_GameplayMap_Spell12;
    private readonly InputAction m_GameplayMap_Spell13;
    private readonly InputAction m_GameplayMap_Spell14;
    private readonly InputAction m_GameplayMap_Spell15;
    private readonly InputAction m_GameplayMap_Spell16;
    private readonly InputAction m_GameplayMap_Click;
    private readonly InputAction m_GameplayMap_AltClick;
    private readonly InputAction m_GameplayMap_AltDoubleClick;
    private readonly InputAction m_GameplayMap_SwitchAutoMode;
    private readonly InputAction m_GameplayMap_ShiftMouse;
    private readonly InputAction m_GameplayMap_ScrollMouse;
    private readonly InputAction m_GameplayMap_ShowMenu;
    private readonly InputAction m_GameplayMap_ShowSource;
    private readonly InputAction m_GameplayMap_SpaceMouse;
    /// <summary>
    /// Provides access to input actions defined in input action map "GameplayMap".
    /// </summary>
    public struct GameplayMapActions
    {
        private @StandardInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GameplayMapActions(@StandardInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_GameplayMap_Move;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell1".
        /// </summary>
        public InputAction @Spell1 => m_Wrapper.m_GameplayMap_Spell1;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell2".
        /// </summary>
        public InputAction @Spell2 => m_Wrapper.m_GameplayMap_Spell2;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell3".
        /// </summary>
        public InputAction @Spell3 => m_Wrapper.m_GameplayMap_Spell3;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell4".
        /// </summary>
        public InputAction @Spell4 => m_Wrapper.m_GameplayMap_Spell4;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell5".
        /// </summary>
        public InputAction @Spell5 => m_Wrapper.m_GameplayMap_Spell5;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell6".
        /// </summary>
        public InputAction @Spell6 => m_Wrapper.m_GameplayMap_Spell6;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell7".
        /// </summary>
        public InputAction @Spell7 => m_Wrapper.m_GameplayMap_Spell7;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell8".
        /// </summary>
        public InputAction @Spell8 => m_Wrapper.m_GameplayMap_Spell8;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell9".
        /// </summary>
        public InputAction @Spell9 => m_Wrapper.m_GameplayMap_Spell9;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell10".
        /// </summary>
        public InputAction @Spell10 => m_Wrapper.m_GameplayMap_Spell10;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell11".
        /// </summary>
        public InputAction @Spell11 => m_Wrapper.m_GameplayMap_Spell11;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell12".
        /// </summary>
        public InputAction @Spell12 => m_Wrapper.m_GameplayMap_Spell12;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell13".
        /// </summary>
        public InputAction @Spell13 => m_Wrapper.m_GameplayMap_Spell13;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell14".
        /// </summary>
        public InputAction @Spell14 => m_Wrapper.m_GameplayMap_Spell14;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell15".
        /// </summary>
        public InputAction @Spell15 => m_Wrapper.m_GameplayMap_Spell15;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Spell16".
        /// </summary>
        public InputAction @Spell16 => m_Wrapper.m_GameplayMap_Spell16;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/Click".
        /// </summary>
        public InputAction @Click => m_Wrapper.m_GameplayMap_Click;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/AltClick".
        /// </summary>
        public InputAction @AltClick => m_Wrapper.m_GameplayMap_AltClick;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/AltDoubleClick".
        /// </summary>
        public InputAction @AltDoubleClick => m_Wrapper.m_GameplayMap_AltDoubleClick;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/SwitchAutoMode".
        /// </summary>
        public InputAction @SwitchAutoMode => m_Wrapper.m_GameplayMap_SwitchAutoMode;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/ShiftMouse".
        /// </summary>
        public InputAction @ShiftMouse => m_Wrapper.m_GameplayMap_ShiftMouse;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/ScrollMouse".
        /// </summary>
        public InputAction @ScrollMouse => m_Wrapper.m_GameplayMap_ScrollMouse;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/ShowMenu".
        /// </summary>
        public InputAction @ShowMenu => m_Wrapper.m_GameplayMap_ShowMenu;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/ShowSource".
        /// </summary>
        public InputAction @ShowSource => m_Wrapper.m_GameplayMap_ShowSource;
        /// <summary>
        /// Provides access to the underlying input action "GameplayMap/SpaceMouse".
        /// </summary>
        public InputAction @SpaceMouse => m_Wrapper.m_GameplayMap_SpaceMouse;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_GameplayMap; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GameplayMapActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GameplayMapActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GameplayMapActions" />
        public void AddCallbacks(IGameplayMapActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayMapActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Spell1.started += instance.OnSpell1;
            @Spell1.performed += instance.OnSpell1;
            @Spell1.canceled += instance.OnSpell1;
            @Spell2.started += instance.OnSpell2;
            @Spell2.performed += instance.OnSpell2;
            @Spell2.canceled += instance.OnSpell2;
            @Spell3.started += instance.OnSpell3;
            @Spell3.performed += instance.OnSpell3;
            @Spell3.canceled += instance.OnSpell3;
            @Spell4.started += instance.OnSpell4;
            @Spell4.performed += instance.OnSpell4;
            @Spell4.canceled += instance.OnSpell4;
            @Spell5.started += instance.OnSpell5;
            @Spell5.performed += instance.OnSpell5;
            @Spell5.canceled += instance.OnSpell5;
            @Spell6.started += instance.OnSpell6;
            @Spell6.performed += instance.OnSpell6;
            @Spell6.canceled += instance.OnSpell6;
            @Spell7.started += instance.OnSpell7;
            @Spell7.performed += instance.OnSpell7;
            @Spell7.canceled += instance.OnSpell7;
            @Spell8.started += instance.OnSpell8;
            @Spell8.performed += instance.OnSpell8;
            @Spell8.canceled += instance.OnSpell8;
            @Spell9.started += instance.OnSpell9;
            @Spell9.performed += instance.OnSpell9;
            @Spell9.canceled += instance.OnSpell9;
            @Spell10.started += instance.OnSpell10;
            @Spell10.performed += instance.OnSpell10;
            @Spell10.canceled += instance.OnSpell10;
            @Spell11.started += instance.OnSpell11;
            @Spell11.performed += instance.OnSpell11;
            @Spell11.canceled += instance.OnSpell11;
            @Spell12.started += instance.OnSpell12;
            @Spell12.performed += instance.OnSpell12;
            @Spell12.canceled += instance.OnSpell12;
            @Spell13.started += instance.OnSpell13;
            @Spell13.performed += instance.OnSpell13;
            @Spell13.canceled += instance.OnSpell13;
            @Spell14.started += instance.OnSpell14;
            @Spell14.performed += instance.OnSpell14;
            @Spell14.canceled += instance.OnSpell14;
            @Spell15.started += instance.OnSpell15;
            @Spell15.performed += instance.OnSpell15;
            @Spell15.canceled += instance.OnSpell15;
            @Spell16.started += instance.OnSpell16;
            @Spell16.performed += instance.OnSpell16;
            @Spell16.canceled += instance.OnSpell16;
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @AltClick.started += instance.OnAltClick;
            @AltClick.performed += instance.OnAltClick;
            @AltClick.canceled += instance.OnAltClick;
            @AltDoubleClick.started += instance.OnAltDoubleClick;
            @AltDoubleClick.performed += instance.OnAltDoubleClick;
            @AltDoubleClick.canceled += instance.OnAltDoubleClick;
            @SwitchAutoMode.started += instance.OnSwitchAutoMode;
            @SwitchAutoMode.performed += instance.OnSwitchAutoMode;
            @SwitchAutoMode.canceled += instance.OnSwitchAutoMode;
            @ShiftMouse.started += instance.OnShiftMouse;
            @ShiftMouse.performed += instance.OnShiftMouse;
            @ShiftMouse.canceled += instance.OnShiftMouse;
            @ScrollMouse.started += instance.OnScrollMouse;
            @ScrollMouse.performed += instance.OnScrollMouse;
            @ScrollMouse.canceled += instance.OnScrollMouse;
            @ShowMenu.started += instance.OnShowMenu;
            @ShowMenu.performed += instance.OnShowMenu;
            @ShowMenu.canceled += instance.OnShowMenu;
            @ShowSource.started += instance.OnShowSource;
            @ShowSource.performed += instance.OnShowSource;
            @ShowSource.canceled += instance.OnShowSource;
            @SpaceMouse.started += instance.OnSpaceMouse;
            @SpaceMouse.performed += instance.OnSpaceMouse;
            @SpaceMouse.canceled += instance.OnSpaceMouse;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GameplayMapActions" />
        private void UnregisterCallbacks(IGameplayMapActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Spell1.started -= instance.OnSpell1;
            @Spell1.performed -= instance.OnSpell1;
            @Spell1.canceled -= instance.OnSpell1;
            @Spell2.started -= instance.OnSpell2;
            @Spell2.performed -= instance.OnSpell2;
            @Spell2.canceled -= instance.OnSpell2;
            @Spell3.started -= instance.OnSpell3;
            @Spell3.performed -= instance.OnSpell3;
            @Spell3.canceled -= instance.OnSpell3;
            @Spell4.started -= instance.OnSpell4;
            @Spell4.performed -= instance.OnSpell4;
            @Spell4.canceled -= instance.OnSpell4;
            @Spell5.started -= instance.OnSpell5;
            @Spell5.performed -= instance.OnSpell5;
            @Spell5.canceled -= instance.OnSpell5;
            @Spell6.started -= instance.OnSpell6;
            @Spell6.performed -= instance.OnSpell6;
            @Spell6.canceled -= instance.OnSpell6;
            @Spell7.started -= instance.OnSpell7;
            @Spell7.performed -= instance.OnSpell7;
            @Spell7.canceled -= instance.OnSpell7;
            @Spell8.started -= instance.OnSpell8;
            @Spell8.performed -= instance.OnSpell8;
            @Spell8.canceled -= instance.OnSpell8;
            @Spell9.started -= instance.OnSpell9;
            @Spell9.performed -= instance.OnSpell9;
            @Spell9.canceled -= instance.OnSpell9;
            @Spell10.started -= instance.OnSpell10;
            @Spell10.performed -= instance.OnSpell10;
            @Spell10.canceled -= instance.OnSpell10;
            @Spell11.started -= instance.OnSpell11;
            @Spell11.performed -= instance.OnSpell11;
            @Spell11.canceled -= instance.OnSpell11;
            @Spell12.started -= instance.OnSpell12;
            @Spell12.performed -= instance.OnSpell12;
            @Spell12.canceled -= instance.OnSpell12;
            @Spell13.started -= instance.OnSpell13;
            @Spell13.performed -= instance.OnSpell13;
            @Spell13.canceled -= instance.OnSpell13;
            @Spell14.started -= instance.OnSpell14;
            @Spell14.performed -= instance.OnSpell14;
            @Spell14.canceled -= instance.OnSpell14;
            @Spell15.started -= instance.OnSpell15;
            @Spell15.performed -= instance.OnSpell15;
            @Spell15.canceled -= instance.OnSpell15;
            @Spell16.started -= instance.OnSpell16;
            @Spell16.performed -= instance.OnSpell16;
            @Spell16.canceled -= instance.OnSpell16;
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @AltClick.started -= instance.OnAltClick;
            @AltClick.performed -= instance.OnAltClick;
            @AltClick.canceled -= instance.OnAltClick;
            @AltDoubleClick.started -= instance.OnAltDoubleClick;
            @AltDoubleClick.performed -= instance.OnAltDoubleClick;
            @AltDoubleClick.canceled -= instance.OnAltDoubleClick;
            @SwitchAutoMode.started -= instance.OnSwitchAutoMode;
            @SwitchAutoMode.performed -= instance.OnSwitchAutoMode;
            @SwitchAutoMode.canceled -= instance.OnSwitchAutoMode;
            @ShiftMouse.started -= instance.OnShiftMouse;
            @ShiftMouse.performed -= instance.OnShiftMouse;
            @ShiftMouse.canceled -= instance.OnShiftMouse;
            @ScrollMouse.started -= instance.OnScrollMouse;
            @ScrollMouse.performed -= instance.OnScrollMouse;
            @ScrollMouse.canceled -= instance.OnScrollMouse;
            @ShowMenu.started -= instance.OnShowMenu;
            @ShowMenu.performed -= instance.OnShowMenu;
            @ShowMenu.canceled -= instance.OnShowMenu;
            @ShowSource.started -= instance.OnShowSource;
            @ShowSource.performed -= instance.OnShowSource;
            @ShowSource.canceled -= instance.OnShowSource;
            @SpaceMouse.started -= instance.OnSpaceMouse;
            @SpaceMouse.performed -= instance.OnSpaceMouse;
            @SpaceMouse.canceled -= instance.OnSpaceMouse;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GameplayMapActions.UnregisterCallbacks(IGameplayMapActions)" />.
        /// </summary>
        /// <seealso cref="GameplayMapActions.UnregisterCallbacks(IGameplayMapActions)" />
        public void RemoveCallbacks(IGameplayMapActions instance)
        {
            if (m_Wrapper.m_GameplayMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GameplayMapActions.AddCallbacks(IGameplayMapActions)" />
        /// <seealso cref="GameplayMapActions.RemoveCallbacks(IGameplayMapActions)" />
        /// <seealso cref="GameplayMapActions.UnregisterCallbacks(IGameplayMapActions)" />
        public void SetCallbacks(IGameplayMapActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GameplayMapActions" /> instance referencing this action map.
    /// </summary>
    public GameplayMapActions @GameplayMap => new GameplayMapActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "GameplayMap" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GameplayMapActions.AddCallbacks(IGameplayMapActions)" />
    /// <seealso cref="GameplayMapActions.RemoveCallbacks(IGameplayMapActions)" />
    public interface IGameplayMapActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell5(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell6" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell6(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell7" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell7(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell8" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell8(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell9" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell9(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell10" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell10(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell11" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell11(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell12" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell12(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell13" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell13(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell14" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell14(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell15" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell15(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Spell16" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpell16(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Click" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "AltClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAltClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "AltDoubleClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAltDoubleClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SwitchAutoMode" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSwitchAutoMode(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ShiftMouse" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnShiftMouse(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ScrollMouse" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnScrollMouse(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ShowMenu" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnShowMenu(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ShowSource" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnShowSource(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SpaceMouse" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpaceMouse(InputAction.CallbackContext context);
    }
}
